import { enrollWithCode } from "@/lib/services/devices";
import { fromServiceResult, jsonError, readJsonBody } from "@/lib/api/respond";

/** A staff phone trades a one-time code (generated by the owner from
 * Settings) for a device session — it never learns APP_PASSWORD. */
export async function POST(req: Request) {
  const body = await readJsonBody(req);
  if (!body || typeof body !== "object") {
    return jsonError("Body permintaan tidak valid.", 400);
  }
  const { code, nama } = body as Record<string, unknown>;
  if (typeof code !== "string" || !code.trim()) {
    return jsonError("Kode wajib diisi.", 400);
  }

  const result = await enrollWithCode({
    code,
    nama: typeof nama === "string" ? nama : undefined,
  });
  return fromServiceResult(result, 201);
}
